proxy_server/proxy_app/urls.py
from django.urls import path
from . import views

app_name = 'proxy_app'

urlpatterns = [
    path('', views.index, name='index'),
    path("add/", views.add_network, name="add"),
    path("edit/<int:pk>/", views.edit_network, name="edit"),
    path("delete/<int:pk>/", views.delete_network, name="delete"),
    path("toggle/<int:pk>/", views.toggle_network, name="toggle"),
]

proxy_server/proxy_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("proxy_app.urls", namespace="proxy_app")),
]

proxy_server/proxy_app/models.py
from django.db import models


class NetworkRule(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    host = models.CharField(max_length=255)
    path_prefix = models.CharField(max_length=255, blank=True)
    response_code= models.IntegerField(default=500)
    enable = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

def __str__(self):
    return f"{self.name}({self.path_prefix}{self.response_code})"

proxy_server/proxy_app/forms.py
from django import forms
from .models import NetworkRule

class NetworkForm(forms.ModelForm):
    class Meta:
        model = NetworkRule
        fields = ['name', 'host', 'path_prefix', 'enable', 'response_code']
        widgets = {
            'response_body': forms.Textarea(attrs={'rows':4, 'cols':40})
        }

proxy_server/proxy_app/views.py
import json
import os
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from .models import NetworkRule
from django.urls import reverse
from .forms import NetworkForm
from django.views.decorators.http import require_POST


NETWORKS_FILE = os.path.join(settings.BASE_DIR, "networks.json")

def write_networks_file():
    qs = NetworkRule.objects.filter(enable=True)
    data = []
    for r in qs:
        data.append({
            "name": r.name,
            "host": r.host,
            "path_prefix": r.path_prefix,
            "response_code": r.response_code,
        })
    with open(NETWORKS_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

def index(request):
    networks = NetworkRule.objects.all().order_by("-updated_at")
    return render(request, "proxy_app/index.html", {"networks": networks})

def add_network(request):
    if request.method == "POST":
        form = NetworkForm(request.POST)
        if form.is_valid():
            form.save()
            write_networks_file()
            return redirect("proxy_app:index")
    else:
        form = NetworkForm()
    return render(request, "proxy_app/form.html", {"form": form})

def edit_network(request, pk):
    obj = get_object_or_404(NetworkRule, pk=pk)
    if request.method == "POST":
        form = NetworkForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            write_networks_file()
            return redirect("proxy_app:index")
    else:
        form = NetworkForm(instance=obj)
    return render(request, "proxy_app/form.html", {"form": form, "edit": True})

def delete_network(request, pk):
    obj = get_object_or_404(NetworkRule, pk=pk)
    if request.method == "POST":
        obj.delete()
        write_networks_file()
        return redirect("proxy_app:index")
    return redirect(request, "proxy_app/index.html")

@require_POST
def toggle_network(request, pk):
    obj = get_object_or_404(NetworkRule, pk=pk)
    obj.enable = not obj.enable
    obj.save()
    write_networks_file()
    return redirect(reverse("proxy_app:index"))

proxy_server/proxy_app/templates/proxy_app/delete.html
<!doctype html>
<html>
<head><meta charset="utf-8"><title>Delete</title></head>
<body>
  <h1>Delete "{{ object }}"?</h1>
  <form method="post">{% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
  <p><a href="{% url 'proxy_app:index' %}">Cancel</a></p>
</body>
</html>

proxy_server/proxy_app/templates/proxy_app/form.html
    {% load static %}
    <!doctype html>
    <html>
    <head><meta charset="utf-8"><title>{% if edit %}Edit{% else %}Add{% endif %}</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
    <div class="aurora-background"></div>

      <h1>{% if edit %}Edit{% else %}Add{% endif %} rule</h1>
        <div class="form-card" >
          <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
                    <button type="submit">Save</button>

                  <a href="{% url 'proxy_app:index' %}">
                      <button type="button">Cancel</button>
                  </a>
          </form>
        </div>
    </body>
    </html>

proxy_server/proxy_app/templates/proxy_app/index.html
{% load static %}
<!doctype html>
<html>
<head><meta charset="utf-8"><title>Networks</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
  <div class="aurora-background"></div>
    <header>
        <h1 class="h1">Network Rules</h1>
    </header>
  <p><a href="{% url 'proxy_app:add' %}">
     <button class="knopka "type="button">Add Network</button>
 </a></p>
<div class="table-container" >
  <div class="glass-card">
    <table border="1" cellpadding="6">
      <tr>
        <th>name</th>
        <th>host</th>
        <th>path_prefix</th>
        <th>enabled</th>
        <th>actions</th>
      </tr>

      {% for n in networks %}
      <tr>
          <div class="lines-table">
        <td>{{ n.name }}</td>
        <td>{{ n.host }}</td>
        <td>{{ n.path_prefix }}</td>
        <td>
          <form method="post" action="{% url 'proxy_app:toggle' n.pk %}">
            {% csrf_token %}
            <input type="checkbox" name="enable" id="enable-{{ n.pk }}" {% if n.enable %}checked{% endif %} onchange="this.form.submit()">
          </form>
        </td>
        <td>
          <a href="{% url 'proxy_app:edit' n.pk %}">
            <button type="button">Edit</button>
          </a>
          <form method="post" action="{% url 'proxy_app:delete' n.pk %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit">Delete</button>
          </form>
        </td>
          </div>
      </tr>
      {% empty %}
      <tr><td colspan="5">No rules</td></tr>
      {% endfor %}
    </table>
  </div>
</div>
</body>
</html>